apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-deployment
  namespace: guetta
spec:
  selector:
    matchLabels:
      app: player
  template:
    metadata:
      labels:
        app: player
    spec:
      containers:
      - name: player
        image: redbaty/guetta:player-js
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: guetta-player-js-envs
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guetta-player-js-envs
  namespace: guetta 
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  TOKEN: "ODU0NTMyODkyNDE2MTQ3NTI2.YMlTxg.ANgMnCJFbUZgRmhVeTvccWhwfgg"
  REDIS_HOST: "redis-service.guetta"
  REDIS_PORT: "6379"